### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by Tachaeon** [damienvanrobaeys/Intune-Reporting#6]
https://www.systanddeploy.com/2024/09/lenovo-devices-warranty-dashboard-with.html

- Runbook.ps1: Azure Automation script
- Assign_permissions.ps1

- **_Workbook.json: Log Analytics dashboard_**
- DCR_Table.json: Table to ingest in DCR

Reading your blog the bolded file is missing from the repo.

**Comment by damienvanrobaeys** [comment]
just uploaded the file, sorry

**Comment by Tachaeon** [comment]
thanks!
